### ISSUE TITLE
what are pros and cons of this store if we use this in place of cookie store

### ISSUE THREAD

**Issue by shozabnadeem** [rails/activerecord-session_store#195] opened 2022-11-16 05:25 UTC
Hi, I want to know about the trade-off of using this store instead of the session store 
 like the effect on performance
 
 I get a few pros such as it is more secure as we store sessions on the server side and invalidate sessions by deleting them from the database but I can't find anything on the performance

**Comment by byroot** [comment] 2023-08-15 13:20
Duplicate of https://github.com/rails/activerecord-session_store/issues/193

**Closed by byroot** 2023-08-15 13:20 UTC
